### PR TITLE
Add Pagination component

### LINKED ISSUE #217: New Component: Pagination
**New component name:** Pagination

**Package this component should live in:** Core

**Context**

**Examples**

### PR DESCRIPTION
**Pull request by lederer**
## Overview

Adds a Pagination component. Requires `currentPage`, `pageCount`, and `onPageChange` props.

### Checklist

- [x] Relevant documentation pages have been created or updated
- [x] Description of PR is in an appropriate section of the changelog and grouped with similar changes if possible
- [ ] Relevant status has been updated on the status page

### Upgrade instructions

If there are any of the following in this PR, provide proper instructions on how to upgrade:

- [ ] Changes to the prop names or types of existing components
- [ ] Changes in intended behavior of existing component props
- [ ] Changes in the theme file's structure
- [ ] A required version bump to a non-dev dependency of the project

### Demo

image

### Notes

~Prev/next icons currently don't match first/last icons. Will be fixed in an upcoming icons pass.~

## Testing Instructions

- Fiddle around with Pagination docs page

Closes #217

### CODE REVIEW

**Comment by designmatty** [comment]
I just realized using those icons in a public repo goes against the license for FA pro. We'll need to remove them from this repo.

I've whipped some icons together based on the arrow-left and arrow-right icons. Please replace with these and do a force push.

[_arrow-icons.zip](https://github.com/raster-foundry/blasterjs/files/3494155/_arrow-icons.zip)

**Comment by lederer** [comment]
Icons replaced. Thanks for crafting.

**Review by designmatty — CHANGES_REQUESTED** [review]
Currently, there's no easy way to override the button styles within the pagination. 

Could you add props like `buttonIntent` and `buttonAppearance` to the `Pagination` component which would get passed down to the `Button` components?

This would allow users to do some quick overrides like this:
image

**Comment by lederer** [comment]
👍  Ready for another look.

**Comment by lederer** [comment]
Snuck in a drive-by typo fix in the Badge component.

**Comment by lederer** [comment]
Slipped in another drive-by fix, for a missing import in the Icon component.

**Review by designmatty — APPROVED** [review]
Looks good

**Pull request merged**
