### PR TITLE
cleans up overall configuration of repo

### LINKED ISSUE #84: Remove all React Styleguidist things
- clean dependencies
- make sure CLI commands don't reference component `README.md` files
- remove `docsApp` directory

### LINKED ISSUE #101: Migrate existing .md docs to .mdx and fix directories
- [ ] Migrate all relevant docs in the `docs` directory to .mdx files
- [ ] Remove any non-relevant files in `docs` (anything referring to styleguidist)
- [ ] Move contents of `docz` directory to `docs`
- [ ] Update `.doczrc.js` to use `docs` directory instead of `docz`
- [ ] Remove `docz` directory

### PR DESCRIPTION
**Pull request by designmatty**
## Overview

- Moves away from yarn in favor of npm
  - This was done because lerna uses npm and was creating `package-lock.json` files.
  - updates all files that used yarn including travis and netlify.toml
- Encourage use of `npm run SCRIPT` over running `./scripts/SCRIPT`
- Removes react-styleguidest
- Updates docz folder location to `./docs` from `./docz`
  - Moved applicable `md` files from old `./docs` to new location and changed to `.mdx`
- Start tracking `.vscode` settings

### Checklist

- [ ] Relevant documentation pages have been created or updated
- [ ] Description of PR is in an appropriate section of the changelog and grouped with similar changes if possible

## Testing Instructions

 * Test all npm scripts to ensure they still work.

Closes #101
Closed #84

### CODE REVIEW

**Review by rbreslow — COMMENTED** [review]
I think it would be valuable to bring some of the stuff in `scripts/` in line with [STRTA](https://github.com/azavea/architecture/blob/master/doc/arch/adr-0000-scripts-to-rule-them-all.md). 

For example, we could move the command in the `netlify.toml` file into a `cibuild` script.

**Comment by alkamin** [comment]
@rbreslow So one problem we ran into was that running commands that reference things in `node_modules` (such as `lerna`) will require that we specify the full path to the executable unless we launch it via `npm run` which correctly handles the path. This caused us to intentionally move away from STRTA for most things. There's probably a good solution for this.

**Review by alkamin — APPROVED** [review]

**Comment by rbreslow** [comment]
@alkamin I don't know of any great solutions. I think it would be valuable even for stuff like this:

https://github.com/azavea/idb-osm-extraction-tool/blob/develop/scripts/server

We use STRTA in some projects just to invoke `$ npm run` commands.

**Comment by alkamin** [comment]
Ah, yeah good call! I'll make an issue to get things in line.

**Pull request merged**
