### PR TITLE
Feature/sml/theme

### LINKED ISSUE #149: Cleanup: A

### LINKED ISSUE #151: Cleanup: Swatch

### LINKED ISSUE #156: Cleanup: Image

### LINKED ISSUE #196: Cleanup: Card

### LINKED ISSUE #197: Cleanup: Text

### PR DESCRIPTION
**Pull request by lederer**
## Target Branch
Note this is a request to merge to `feature/theme`, not `develop`. All theme-related PRs should target `feature/theme` until the theme upgrade is complete.

## Overview

Updates the following components to the new theme system:

- Card
- Text
- Heading
- A
- Divider
- Image
- ProgressBar
- Swatch

Docz pages have been updated for accuracy, but not overhauled in any way.

### Checklist

- [x] Relevant documentation pages have been created or updated
- [x] Description of PR is in an appropriate section of the changelog and grouped with similar changes if possible
- [x] Relevant status has been updated on the status page

### Upgrade instructions

If there are any of the following in this PR, provide proper instructions on how to upgrade:

- [x] Changes to the prop names or types of existing components
- [ ] Changes in intended behavior of existing component props
- [ ] Changes in the theme file's structure
- [ ] A required version bump to a non-dev dependency of the project

Props relying on constants in `core/common` have been removed or replaced:
- `Card` `density` removed
- `Image` `shape` replaced with `rounded` and `circle` boolean props
- `Swatch` `shape` replaced with `rounded` and `circle` boolean props

Added `colorFocus` and `colorActive` props to the `A` component.

## Testing Instructions

- Use docz pages and/or testbed app to confirm components work as expected

Closes #196 
Closes #197 
Closes #149 
Closes #156 
Closes #151

### CODE REVIEW

**Review by designmatty — CHANGES_REQUESTED** [review]
**Text component review:**

I think we'll need to include LAYOUT and POSITION props to allow for things like text-overflow clipping, vertical-alignment with icons, etc

**Comment by designmatty** [comment]
**Heading component review:**

I think we'll need to include LAYOUT and POSITION props to allow for things like text-overflow clipping, vertical-alignment with icons, etc

**Comment by designmatty** [comment]
**A component review:**

Update docs to include updated theme schema.

**Comment by designmatty** [comment]
**Card component review:**

Update docs to include updated theme schema.

**Comment by designmatty** [comment]
All other components function as expected.

**Comment by lederer** [comment]
Changes made. Thanks for catching. Ready for another look.

**Review by designmatty — APPROVED** [review]
thanks for making those changes

**Pull request merged**
