### PR TITLE
Dialog

### LINKED ISSUE #35: New component: Modal

### PR DESCRIPTION
**Pull request by lederer**
## Overview

Add the Dialog component ~to the new Overlays package~.

I chose to wrap [react-modal](https://github.com/reactjs/react-modal), since it's the de facto standard and is accessible out of the box. 

I imposed some opinionated layout and transition styles, which cannot be easily overridden, and in fact the component ignores any styles passed in via react-modal's `style` prop. But you can pass in a select set of styled-system props to customize things like size, padding, color, shadow, and scrim opacity.

As far as the dialog contents go, this component is completely agnostic and just renders its children as is. If we want to impose some consistent structure (header, footer, etc) we can come up with subcomponents (DialogHeader, DialogFooter, etc) and/or use slots.

### Checklist

- [x] Relevant documentation pages have been created or updated
- [ ] Description of PR is in an appropriate section of the changelog and grouped with similar changes if possible

Are there any of the following in this PR?

- [ ] Changes to the prop names or types of existing components
- [ ] Changes in intended behavior of existing component props
- [ ] Changes in the theme file's structure
- [ ] A required version bump to a non-dev dependency of the project

If one of the above is checked...

- [ ] information or guidance around needed changes for consumers of this library has been added to the changelog under `Upgrade Instructions`

### Demo

image

### Notes

Added a `shadows` field to defaultTheme as part of this.

## Testing Instructions

 * Open the Dialog docs page 
 * Fiddle with various props: width, height, opacity, boxShadow, etc
 * Take particular note of the `<style>` tag used to inject transition styling.

Closes #35

### CODE REVIEW

**Comment by lederer** [comment]
This looks compelling: https://github.com/AlexanderRichey/styled-react-modal/

Might be worth using it instead. Need to determine its a11y support.

**Comment by lederer** [comment]
This PR wraps [react-modal](https://github.com/reactjs/react-modal). An alternative approach would be to use [styled-react-modal](https://github.com/AlexanderRichey/styled-react-modal), which uses styled-components. 

I've looked through styled-react-modal a bit and while I think it's compelling, I'd rather stick with react-modal for the time being, because:

- react-modal is a widely used de facto standard (with 4400 gh stars), whereas styled-react-modal is fairly nascent (with 48 stars).
- react-modal takes a11y seriously, whereas styled-react-modal doesn't mention it at all, and doesn't set any aria attributes, not even `role="dialog"`. I don't think it would be hard to implement it with a baseline level of a11y, but still.
- react-modal is already implemented in this PR. It works. And we've wrapped it in a styled-component friendly fashion.

That said, we may still need to graduate beyond react-modal at some point if we want to expand the Overlays package to include things like popovers, alerts, toasts, tooltips, context-menus, etc – and if we want them all to share common underlying overlay (haha) code, like [Blueprint](https://blueprintjs.com/docs/#core/components/overlay) and [Evergreen](https://evergreen.segment.com/components) do. But we can cross that bridge when we come to it.

**Comment by lederer** [comment]
Rebased and, per discussion with @designmatty, moved Dialog into the Core package, eliminating the nascent Overlays package. Keeping things simple for now.

**Review by designmatty — APPROVED** [review]
This looks good. I appreciate the consideration of accessibility with this PR. Let's merge and then log an issue to update the documentation to include a fully working example (button to open, able to close, etc). I'd normally say to make that change now, however, creating classes inside the docz playground is broken. So let's keep an eye on this issue https://github.com/pedronauck/docz/issues/567 and once it's resolved setup our documentation to be a bit more robust.

**Pull request merged**
